"$schema" = 'https://starship.rs/config-schema.json'

palette = 'rose_pine'

format = """
[░▒▓](color_iris)\
$os\
$username\
$hostname\
[](bg:color_foam fg:color_iris)\
$directory\
[](fg:color_foam bg:color_overlay)\
$git_branch\
$git_status\
[](fg:color_overlay bg:color_surface)\
$nodejs\
$bun\
$deno\
$python\
$rust\
$golang\
$php\
$java\
$kotlin\
$lua\
$c\
$cpp\
$docker_context\
$conda\
[](fg:color_surface bg:color_hl_low)\
$nix_shell\
[](fg:color_hl_low bg:color_base)\
$time\
[ ](fg:color_base)\
\n$character"""

[palettes.rose_pine]
color_base = '#191724'
color_surface = '#1f1d2e'
color_overlay = '#26233a'
color_muted = '#6e6a86'
color_subtle = '#908caa'
color_text = '#e0def4'
color_love = '#eb6f92'
color_gold = '#f6c177'
color_rose = '#ebbcba'
color_pine = '#31748f'
color_foam = '#9ccfd8'
color_iris = '#c4a7e7'
color_hl_low = '#21202e'
color_hl_med = '#403d52'

[directory]
style = "fg:color_base bg:color_foam"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[username]
style_user = "fg:color_base bg:color_iris"
style_root = "fg:color_base bg:color_love"
format = '[ $user]($style)'
show_always = true
disabled = false

[hostname]
ssh_only = false
format = '[@$hostname ]($style)'
style = "fg:color_base bg:color_iris"
disabled = false

[git_branch]
symbol = ""
style = "bg:color_overlay"
format = '[[ $symbol $branch ](fg:color_foam bg:color_overlay)]($style)'

[git_status]
style = "bg:color_overlay"
format = '[[($all_status$ahead_behind )](fg:color_foam bg:color_overlay)]($style)'

[nodejs]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[bun]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[deno]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[python]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version)(\($virtualenv\)) ](fg:color_foam bg:color_surface)]($style)'

[rust]
symbol = "󱘗"
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[golang]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[php]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[java]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[kotlin]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[lua]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[c]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[cpp]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol ($version) ](fg:color_foam bg:color_surface)]($style)'

[docker_context]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol $context ](fg:color_foam bg:color_surface)]($style)'

[conda]
symbol = ""
style = "bg:color_surface"
format = '[[ $symbol $environment ](fg:color_foam bg:color_surface)]($style)'

[nix_shell]
symbol = ""
style = "bg:color_hl_low"
format = '[[ $symbol $state( \($name\)) ](fg:color_gold bg:color_hl_low)]($style)'
impure_msg = "impure"
pure_msg = "pure"
unknown_msg = "unknown"

[time]
disabled = false
time_format = "%R"
style = "bg:color_base"
format = '[[  $time ](fg:color_subtle bg:color_base)]($style)'

[os]
style = "fg:color_base bg:color_iris"
format = "[ $symbol]($style)"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[character]
success_symbol = '[❯](color_foam)'
error_symbol = '[❯](color_love)'
